# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AssessFeatures <- function(A_mat, columns, rand_sample_size = 1000L, rand_sample_no = 100L, thread_no = -1L) {
    .Call(`_DECODE_AssessFeatures`, A_mat, columns, rand_sample_size, rand_sample_no, thread_no)
}

AssessFeatures_betweenGroups <- function(A_mat, columns_A, columns_B, rand_sample_size = 1000L, rand_sample_no = 100L, thread_no = -1L) {
    .Call(`_DECODE_AssessFeatures_betweenGroups`, A_mat, columns_A, columns_B, rand_sample_size, rand_sample_no, thread_no)
}

ProfileModule <- function(A_mat, rows, rand_sample_size = 1000L, rand_sample_no = 100L, thread_no = -1L) {
    .Call(`_DECODE_ProfileModule`, A_mat, rows, rand_sample_size, rand_sample_no, thread_no)
}

