---
title: "Example usage of DECODE"
author: "Shahin Mohammadi"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = T, warning=FALSE, message = F)
```


### Import expression matrix

```{r}
ds_folder = '../../input/datasets/PBMC_4k_10X'
expr_file = paste(ds_folder, 'expression.txt', sep = '/')
expression = read.table(expr_file, header = T, row.names = NULL)
gene_names = expression[, 1]
expression = expression[, -1]
expression = as.matrix(expression)
```

### Normalize data (if needed)

```{r}
X = as.matrix(expression)
if(max(X) > 50) {
  Sums = colSums(X)
  med = median(Sums)
  X = med*scale(X, center=FALSE, scale=Sums)
  X = log(1 + X)
}
```

### Filter genes that are not expressed in at least 5 cells

```{r}
gene_mask = rowSums(X != 0) >= 10
X = X[gene_mask,]
gene_names = gene_names[gene_mask]
```


### Sparsify
```{r}
library(Matrix)

X_sparse = as(X, "sparseMatrix")
```

### Load sample annotations:

```{r}
annotations = read.table('../../input/datasets/PBMC_4k_10X/sample_annotations.txt', sep='\t', header = T)
```

### Setup parameters

```{r}
thread_no = 8
sample_no = 10000
sample_size = 100
rows = seq(1, dim(X)[1])

```


### Use DECODE to perform preferential analysis between CD8/CD4 T-cells
```{r}
require(DECODE)

cols_CD8 = which(annotations$Full_Labels == "CD8+ Cytotoxic T")
cols_CD4 = which(annotations$Full_Labels == "CD4+/CD45RA+/CD25- Naive T")

Assessment.results = AssessFeatures_betweenGroups(X_sparse, rows, cols_CD8, cols_CD4, sample_size, sample_no, thread_no)

gene_enrichment_scores_CD8_vs_CD4 = Assessment.results$logPval

sorted_markers_CD8_vs_CD4 = data.frame(genes=gene_names[order(gene_enrichment_scores_CD8_vs_CD4, decreasing = TRUE)], scores=sort(gene_enrichment_scores_CD8_vs_CD4, decreasing = TRUE));

sorted_markers_CD8_vs_CD4[1:20, ]
```


### Use DECODE to identify preferential genes in B-cells

```{r}
require(DECODE)

cols = which(annotations$Labels == "B")

Assessment.results = AssessFeatures(X_sparse, rows, cols, sample_size, sample_no, thread_no)

gene_enrichment_scores_B = Assessment.results$logPval


sorted_markers = data.frame(genes=gene_names[order(gene_enrichment_scores_B, decreasing = TRUE)], pval=sort(gene_enrichment_scores_B, decreasing = TRUE))
sorted_markers[1:20, ]

```

```{r}
require(ggplot2)
B_module = which(gene_enrichment_scores_B > 2)
profile_scores = ProfileModule(X_sparse, B_module, sample_size, sample_no, thread_no);

Data = data.frame(x = seq(1, length(profile_scores)), y = profile_scores)

g = ggplot(Data, aes(x,y)) + geom_point() + geom_smooth() + xlab("Cells") + ylab("-log(pval)") 
plot(g)
```

